#!/bin/sh

# Interactively cherry-pick commit(s) selected via fzf
# usage: git chip [git-cherry-pick options]  e.g. git chip -x

commits="$(git log --oneline --color=always \
    | fzf --ansi --multi --reverse --preview 'git show --color=always --stat {1}' \
    | awk '{print $1}')" || exit

if [ -z "$commits" ]; then
    echo "chip: no commit selected" >&2
    exit 1
fi

# shellcheck disable=SC2086
git cherry-pick "$@" $commits
