#!/bin/sh
mode="normal"
case "$1" in
    --amend)   mode="amend"; shift ;;
    --no-edit) mode="no-edit"; shift ;;
esac

if [ "$mode" != "no-edit" ]; then
    message="${1}"
    if [ -z "$message" ]; then
        message="sync: $(whoami)@$(hostname) $(date '+%Y-%m-%d %H:%M:%S')"
        echo using message $message
    else
        shift
    fi

    if [ -e "$message" ]; then
        echo message "$message" cannot be a path
        exit 1
    fi
fi

if [ -n "${@}" ]; then
    git a "${@}"
fi

case "$mode" in
    normal)   git commit -m "$message" ;;
    amend)    git commit --amend -m "$message" ;;
    no-edit)  git commit --amend --no-edit ;;
esac
