#!/bin/sh
lang=${1}
if [ -z ${lang} ]; then
    lang=$(curl -s https://api.github.com/repos/github/gitignore/contents | jq -r '.[].name' | grep 'gitignore$' | sed 's/.gitignore$//' | fzf)
fi
if [ -z ${lang} ]; then
    return
fi
curl -s https://raw.githubusercontent.com/github/gitignore/refs/heads/main/${lang}.gitignore
