#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)

branch=$(echo "$branch" | tr '[:upper:]' '[:lower:]')
branch=$(echo "$branch" | sed -E 's/[^a-zA-Z0-9-]+/-/g')
branch=$(echo "$branch" | sed -E 's/^-+//g')
branch=$(echo "$branch" | sed -E 's/-+$//g')

path="./.tmp/$branch"
mkdir -p "$path"

justfile="$path/justfile"

if [ ! -f "$justfile" ]; then
    repo_root=$(git symbolic-ref --short refs/remotes/origin/HEAD | sed 's#^origin/##')
    echo "import \"../$repo_root/justfile\"" >> "$justfile"
    $EDITOR "$justfile"
elif [ "$#" -eq 0 ]; then
    $EDITOR "$justfile"
else
    just -d . -f "$justfile" "${@}"
fi
