#!usr/bin/env sh
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias duh='du -d 1 -h'

alias today='vim -c "Today!"'
alias notes='vim -c "Notes!"'
alias vimpy='vim -c "S uv run ipython"'

alias myip='curl http://ifconfig.me/ip'
alias wttr='curl https://wttr.in/'

alias chz='chezmoi'
alias dotsync='chezmoi managed | xargs chezmoi re-add && git -C $(chezmoi source-path) sync'
alias l='eza'
alias vi='command vim'
alias vim='nvim'

alias least='fmt -w 80 | bat --paging always --style plain'
alias leastmd='least -l markdown'

alias meminfo='free -m -l -t'
alias psmem='ps auxf | sort -nr -k 4'
alias pscpu='ps auxf | sort -nr -k 3'

alias todo='rg -o --hidden --iglob "!.git" --iglob "!TODO.md" "TODO.*"'

alias genoverlaps="touch OVERLAPS.md && aider OVERLAPS.md --message-file ~/.aider/message_files/overlaps.md"

# mcdir () { mkdir "$1" && cd "$_" }
# joke () { curl https://icanhazdadjoke.com/; echo "" }
# shitcommit () { curl https:///whatthecommit.com/index.txt; echo "" }


# Quick cd command
alias c='cd "$(find . -maxdepth 1 -type d | fzf)"'
alias C='cd "$(find . -type d | fzf)"'
# Quick project navigation command
alias g='cd $(fd ".git$" ~/Workspace/repos -H -I -d 5 -x dirname {} \; | fzf)'
alias t='tmux'
alias a='tmux a'
alias d='tmux detach'
# Quick arglist filler for vim
alias vimm='vim $(find -type f -not -path '\''*/\.git/*'\'' -printf '\''%P\n'\'' | fzf -m | tr '\'' '\'' _)'
# Muscle memory
alias q="exit"
alias G="git"
alias Git="git"

# More aliases
alias setclip="xclip -selection c"
alias getclip="xclip -selection c -o"

brew() {
  case "$1" in
    update)
      command bundle install --file="${HOME}/Brewfile" || true
      ;;
  esac

  command brew "$@"

  case "$1" in
    install|uninstall|remove)
      # update Brewfile in current directory (or change path)
      command brew bundle dump
      ;;
  esac
}
