#!/usr/bin/env bash
list=(
    "awk"
    "bat"
    "bitwarden-cli"
    "coreutils"
    "ctags"
    "curl"
    "diffutils"
    "duckdb"
    "fd"
    "findutils"
    "fzf"
    "gh"
    "git"
    "gnu-sed"
    "grep"
    "hugo"
    "jq"
    "less"
    "mise"
    "nano"
    "neofetch"
    "pandoc"
    "rg"
    "starship"
    "tealdeer"
    "tmux"
    "tree"
    "wget"
)
for item in "${list[@]}"; do
    brew install $item
done

