#!/usr/bin/env bash
[ -f /home/linuxbrew/.linuxbrew/bin/brew ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
[ -f /opt/homebrew/bin/brew ] && eval "$(/opt/homebrew/bin/brew shellenv)"

list=(
    "dprint"
    "prettier"  # css html markdown yaml js
    "cspell"
    "shfmt"
    "write-good"
    "jq"
    "jsonlint"
    "checkmake"
    "sqlfluff"

    "aider"
    "awk"
    "bat"
    "bitwarden-cli"
    "coreutils"
    "ctags"
    "curl"
    "datasette"
    "diffutils"
    "duckdb"
    "fd"
    "findutils"
    "fzf"
    "gh"
    "git"
    "gnu-sed"
    "grep"
    "hugo"
    "just"
    "less"
    "llm"
    "mdformat"
    "mise"
    "nano"
    "pandoc"
    "pre-commit"
    "python-lsp-server"
    "rg"
    "shellcheck"
    "sqlite-utils"
    "starship"
    "tealdeer"
    "tmux"
    "tree"
    "vint"
    "wget"
)
for item in "${list[@]}"; do
    if brew list --formula | grep -q "^${item}$"; then
        echo "Upgrading $item..."
        brew upgrade $item
    else
        echo "Installing $item..."
        brew install $item
    fi
done

# macOS-specific casks
casks=(
    "caffeine"
    "docker"
    "firefox"
    "font-jetbrains-mono-nerd-font"
    "iterm2"
    "macmediakeyforwarder"
    "protonvpn"
    "rectangle"
    "slack"
    "spotify"
    "wezterm"
    "write"
)
if [[ "$OSTYPE" == "darwin"* ]]; then

    for cask in "${casks[@]}"; do
        if brew list --cask | grep -q "^${cask}$"; then
            echo "Upgrading cask $cask..."
            brew upgrade --cask $cask
        else
            echo "Installing cask $cask..."
            brew install --cask $cask
        fi
    done
fi
