{ pkgs ? import <nixpkgs> {} }:

with pkgs;

[
    R
    bat
    coreutils-full
    dprint
    dprint-plugins.dprint-plugin-markdown
    curlFull
    diffutils
    docker
    dotenvx
    eza
    fd
    findutils
    firefox
    fzf
    gawk
    gh
    ghostty
    git
    git-lfs
    gitleaks
    glab
    glow
    gnugrep
    gnused
    herdr
    jdt-language-server
    jq
    jsongrep
    julia
    just
    less
    (llm.withPlugins {
      llm-openrouter = true;
    })
    llmfit
    lua-language-server
    marksman
    mdformat
    mise
    monolith
    nano
    neovim
    nerd-fonts.jetbrains-mono
    nodejs_26
    pandoc
    pi-coding-agent
    podman
    pre-commit
    python313
    python313Packages.files-to-prompt
    python313Packages.mdformat-front-matters
    python313Packages.mdformat-gfm
    python313Packages.python-lsp-server
    python313Packages.symbex
    radian
    ripgrep
    ruff
    shellcheck
    shfmt
    skim
    slides
    spotify
    sqlfluff
    starship
    strip-tags
    stylua
    taplo
    tealdeer
    terraform
    terraform-ls
    tree
    unixtools.arp
    unixtools.col
    unixtools.column
    unixtools.fdisk
    unixtools.fsck
    unixtools.getopt
    unixtools.ifconfig
    unixtools.net-tools
    unixtools.netstat
    unixtools.ping
    unixtools.procps
    unixtools.quota
    unixtools.route
    unixtools.script
    unixtools.top
    unixtools.util-linux
    unixtools.wall
    unixtools.watch
    unixtools.whereis
    unixtools.write
    unixtools.xxd
    uv
    wget
    write-good
    yamlfmt
] ++ (if stdenv.isDarwin then [
    rectangle
    caffeine
    slack
] else [])
