# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: openrouter:google/gemini-2.5-flash
clients:
- type: openai-compatible
  name: openrouter
  api_base: https://openrouter.ai/api/v1
